# Install NumPy

In [ ]:
!pip install numpy

# Import NumPy

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]
type(a)

list

In [11]:
b = np.array([1, 2, 3])
type(b)

numpy.ndarray

In [12]:
print(a)
print(b)

[1, 2, 3]
[1 2 3]


In [21]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
axis=1

array([[1],
       [2]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.empty((5, 5))

array([[6.23042070e-307, 1.42417221e-306, 1.60219306e-306,
        7.56593017e-307, 7.56587584e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511562e-306, 6.23055651e-307],
       [7.56599128e-307, 1.24610587e-306, 1.24610723e-306,
        1.42418172e-306, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        8.90029544e-307, 3.20552953e-317]])

In [41]:
np.arange(0, 10, 1) # (start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Add, remove, sort

In [ ]:
np.append
np.delete
np.sort

In [57]:
a = np.array([1, 2, 3])
print(a)
a = np.append(a, 10)
print(a)

[1 2 3]
[ 1  2  3 10]


In [58]:
a = np.delete(a, 1)
print(a)

[ 1  3 10]


In [60]:
a = np.append(a, 2)
print(a)

[ 1  3 10  2]


In [65]:
a

array([ 1,  3, 10,  2])

In [71]:
a = np.insert(a, obj=0, values=100)

In [72]:
a

array([100,   1,   3,  10,   2])

In [73]:
a = np.sort(a)

In [74]:
a

array([  1,   2,   3,  10, 100])

In [76]:
a.ndim

1

In [77]:
b = np.array([[1,2], 
              [3,4]])
b.ndim

2

In [78]:
print(a.size)
print(b.size)

5
4


In [79]:
print(a.shape)
print(b.shape)

(5,)
(2, 2)


In [80]:
np.array([1,2,3,4,5]).

1

In [89]:
a = np.arange(6)
print(a)
print(a.shape)
print()

b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
(6,)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape()

In [90]:
type(a)

numpy.ndarray

In [92]:
a = np.array([1,2,3,4,5])
print(a.shape)

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

a3 = a2[np.newaxis]
print(a3.shape)
print(a3)

(5,)
(1, 5)
[[1 2 3 4 5]]
(1, 1, 5)
[[[1 2 3 4 5]]]


In [95]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 5)
[[1 2 3 4 5]]


In [93]:
a2 = a[: , np.newaxis]
print(a2.shape)
print(a2)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [97]:
a = np.array([1,2,3,4,5])
print(a.shape)
print()

a2 = np.expand_dims(a, axis=1)
print(a2.shape)
print(a2)
print()

a3 = np.expand_dims(a, axis=0)
print(a3.shape)
print(a3)

(5,)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]

(1, 5)
[[1 2 3 4 5]]


In [102]:
a = np.arange(0, 20, 1)
print(a)
print(a[0])
print(a[5])
print(a[1:3])
print(a[8:])
print(a[-5:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0
5
[1 2]
[ 8  9 10 11 12 13 14 15 16 17 18 19]
[15 16 17 18 19]


In [108]:
a = np.array([[1,2,3], 
              [4,5,6],
              [7,8,9]])
print(a)
print()
print(a[a > 5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[6 7 8 9]


In [111]:
lima_keatas = (a > 5)
print(a[lima_keatas])

[6 7 8 9]


In [112]:
lima_keatas = (a > 5)
lapan_kebawah = (a < 8)
print(a[lima_keatas & lapan_kebawah])

[6 7]


In [114]:
lima_keatas = (a > 5)
dua = (a == 2)
print(a[(lima_keatas | dua) & lapan_kebawah])

[2 6 7]


In [119]:
a = np.arange(0, 10, 1)
print(a)
a = a[2:4]
print(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 3]
[2 3]


In [128]:
a = np.array([[2,2],
              [3,3]])

b = np.array([[1,1],
              [2,2]])
print('Vertical / kolom / axis=0')
print(np.vstack((a, b)))
print('horizontal / baris / axis=1')
print(np.hstack((a, b)))

Vertical / kolom / axis=0
[[2 2]
 [3 3]
 [1 1]
 [2 2]]
horizontal / baris / axis=1
[[2 2 1 1]
 [3 3 2 2]]


In [132]:
a = [[1,2,3],
     [2,2,2]]
b = [[4,5,6], 
     [4,4,4]]
a.extend(b)
print(a)

[[1, 2, 3], [2, 2, 2], [4, 5, 6], [4, 4, 4]]


In [124]:
a = np.array([[1,1],
              [2,2]])

b = np.array([[2,2],
              [4,4]])
np.vstack((a, b))

array([[1, 1],
       [2, 2],
       [2, 2],
       [4, 4]])

In [145]:
a = np.arange(0, 21, 1)
b = np.arange(0, 5, 1)

In [136]:
print(a)
print(len(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
20


In [146]:
c = np.hsplit(a, 3)
print(c)
print(c[0].size)
print(c[1].size)

[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18, 19, 20])]
7
7


In [157]:
a = np.array([[1,1],
              [2,2],
              [3,3]])
print(a)
print(len(a))
b = np.vsplit(a, 3)
print(b)
print(len(b))

[[1 1]
 [2 2]
 [3 3]]
3
[array([[1, 1]]), array([[2, 2]]), array([[3, 3]])]
3


In [158]:
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [163]:
print('A')
print(a)
print()

print('B')
b = a.view()
print(b)
print()

print('C')
c = a.copy()
print(c)
print()

A
[[1 1]
 [2 2]
 [3 3]]

B
[[1 1]
 [2 2]
 [3 3]]

C
[[1 1]
 [2 2]
 [3 3]]



In [165]:
a = a[0]
print('A')
print(a)
print()

print('B')
print(b)
print()

print('C')
print(c)
print()

A
[1 1]

B
[[1 1]
 [2 2]
 [3 3]]

C
[[1 1]
 [2 2]
 [3 3]]



In [173]:
a = np.arange(1, 5, 1)
print(a)
print()
print(a.sum())

[1 2 3 4]

10


In [176]:
data = np.array([1,2,3])
tambah = np.array([2,2,2])
data + tambah

array([3, 3, 5])

In [185]:
data = np.array([[1,2,3],
                 [4,5,6]]) # 2x3
tambah = np.array([[2,2,2]]) # 2x1
data + tambah # 2x3

array([[3, 4, 5],
       [6, 7, 8]])

In [190]:
data = np.array([[1,2,3],
                 [4,5,6]]) # 2x3
tambah = np.array([[2,2,2]]) # 1x3
data * tambah # 2x3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [193]:
data = np.array([[1,2,3],
                 [4,5,6]]) # 2x3
tambah = np.array([[2],
                   [2],
                   [2]]) # 3x1
data * tambah # 2x3

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [192]:
data = np.array([[1,2,3],
                 [4,5,6]]) # 2x3
tambah = np.array([[2],
                   [2],
                   [2]]) # 3x1
data + tambah # 2x3

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [188]:
data = np.array([[1,2,3],  # R x C
                 [4,5,6]]) # 2x3
tambah = np.array([[2,2]]) # 2x1
data * tambah # 2x3

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [201]:
            # r x c
print(data) # 2 x 3
print()
print(data.sum()) # jumlah semua
print(data.sum(axis=0)) # jumlah kolom ==> 
print()
print(data.sum(axis=1))

[[1 2 3]
 [4 5 6]]

21
[5 7 9]

[ 6 15]


In [217]:
data = data.T
print(data)

[[1 2 3]
 [4 5 6]]


In [221]:
print(data)
print()
print(data * 2)
print()
print(data * [2,2,2])

[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]

[[ 2  4  6]
 [ 8 10 12]]


In [231]:
data = np.array([[1,2], [3,4]])
print('Data\n', data)
ones = np.ones([2,2])
print('Ones\n', ones)
print('\n', data+ones)

Data
 [[1 2]
 [3 4]]
Ones
 [[1. 1.]
 [1. 1.]]

 [[2. 3.]
 [4. 5.]]


In [230]:
print('Data\n', data)
ones_row = np.ones([1,2])
print('One Row\n', ones_row)
print('\n',data+ones_row)

Data
 [[1 2]
 [3 4]]
One Row
 [[1. 1.]]

 [[2. 3.]
 [4. 5.]]


In [237]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print('size =', a_1.size)
print('shape =', a_1.shape)
print()
a_2 = np.array([[7,8], [9,10], [10,11]])
print(a_2)
print('size =', a_2.size)
print('shape =', a_2.shape)
print()

print('Result')
print(np.dot(a_1, a_2))
print()

print('Result2')
print(a_1 * a_2)

[[1 2 3]
 [4 5 6]]
size = 6
shape = (2, 3)

[[ 7  8]
 [ 9 10]
 [10 11]]
size = 6
shape = (3, 2)

Result
[[ 55  61]
 [133 148]]

Result2


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [249]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print('size =', a_1.size)
print('shape =', a_1.shape)
print()
a_2 = np.array([[7,8], [9,10], [10,11]])
print(a_2)
print('size =', a_2.size)
print('shape =', a_2.shape)
print()

print('Result')
A = np.dot(a_1, a_2)
print(A)
print('size =', A.size)
print('shape =', A.shape)
print()

a_3 = np.array([[2,2,2], [2,2,2]])
print(a_3)
print('size =', a_3.size)
print('shape =', a_3.shape)
print()

print('Result 3')
B = np.dot(A, a_3)
print(B)
print('size =', B.size)
print('shape =', B.shape)
print()
print()

[[1 2 3]
 [4 5 6]]
size = 6
shape = (2, 3)

[[ 7  8]
 [ 9 10]
 [10 11]]
size = 6
shape = (3, 2)

Result
[[ 55  61]
 [133 148]]
size = 4
shape = (2, 2)

[[2 2 2]
 [2 2 2]]
size = 6
shape = (2, 3)

Result 3
[[232 232 232]
 [562 562 562]]
size = 6
shape = (2, 3)




In [268]:
data = np.array([[1,2,3], [4,5,6] , [7,8,9]])
print(data)
#          c0 c1 c2
# r0 --> [[1 2 3]
# r1 --> [4 5 6]
# r2 --> [7 8 9]]

print(data[2, 1])
print(data[0:2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[2 5]


In [267]:
data = np.array([[[1,2],[2,3],[3,4]], [[4,5],[5,6],[6,7]] , [[7,8],[8,9],[9,10]]])
display(data)
print(data.ndim)
print(data.shape)
print(data[0, 1, 1]) # X, Y, Z

# X = 0
# [[ 1,  2],
# [ 2,  3],
# [ 3,  4]]

# Y = 1
# [ 2,  3]

# Z = 1
# 3

array([[[ 1,  2],
        [ 2,  3],
        [ 3,  4]],

       [[ 4,  5],
        [ 5,  6],
        [ 6,  7]],

       [[ 7,  8],
        [ 8,  9],
        [ 9, 10]]])

3
(3, 3, 2)
3


In [272]:
print(data)
print()
print(data.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [278]:
data = np.array([[1,2,3],
                 [0,10,100]])
print(data)
print('shape = ', data.shape)
print()
print(data.reshape(3,2))
print('shape = ', data.reshape(3,2).shape)
print()
print(data.T)
print('shape = ', data.T.shape)

[[  1   2   3]
 [  0  10 100]]
shape =  (2, 3)

[[  1   2]
 [  3   0]
 [ 10 100]]
shape =  (3, 2)

[[  1   0]
 [  2  10]
 [  3 100]]
shape =  (3, 2)


In [293]:
data = np.ones((3, 2, 2, 4))
print(data)
print(np.ones((3, 2, 2, 4)).ndim)
print(np.ones((3, 2, 2, 4)).shape)

print(data[0, 1, 1, 1])

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
4
(3, 2, 2, 4)
1.0


In [319]:
data = np.random.random((3, 2, 2, 3))
print(data)
print()
print('Flattened')
print(data.flatten())
print(data.flatten()[0])

[[[[0.47629429 0.30297454 0.50840885]
   [0.50526103 0.80892036 0.04699076]]

  [[0.10706811 0.8116543  0.91986259]
   [0.4060995  0.66555062 0.52091666]]]


 [[[0.53923598 0.32959938 0.9187962 ]
   [0.59813018 0.9379178  0.50414781]]

  [[0.25131529 0.62663186 0.83694468]
   [0.60978956 0.37934186 0.98060748]]]


 [[[0.56161392 0.91837322 0.71381688]
   [0.22077519 0.87230871 0.33215531]]

  [[0.60686431 0.70413628 0.0078707 ]
   [0.05357255 0.01720735 0.90154233]]]]

Flattened
[0.47629429 0.30297454 0.50840885 0.50526103 0.80892036 0.04699076
 0.10706811 0.8116543  0.91986259 0.4060995  0.66555062 0.52091666
 0.53923598 0.32959938 0.9187962  0.59813018 0.9379178  0.50414781
 0.25131529 0.62663186 0.83694468 0.60978956 0.37934186 0.98060748
 0.56161392 0.91837322 0.71381688 0.22077519 0.87230871 0.33215531
 0.60686431 0.70413628 0.0078707  0.05357255 0.01720735 0.90154233]
0.4762942859217051


## Title
### Subtitle
Halo nama saya:<br>
Fachrul

In [321]:
print(5**2)
print(np.square(5))

25
25


In [ ]:
# 1/n sigma i-n (Yi - Yi>)**
1/n * np.sum(np.square(yi - yi>))